// Every user-facing English string lives here (README §2.2 #7), so an Indonesian locale can be added later.
// Server text is Indonesian; lib/present/labels.ts maps it onto these templates (API_CONTRACT §7).
import type { ScenarioId } from "@aegis/types";

export const TOKEN = "MockUSDG"; // testnet and local both run MockUSDG; never a bare "USDG" beside balances

export const scenarioCopy: Record<ScenarioId, { title: string; description: string }> = {
  "B-dispute": { title: "Dispute settled by proof", description: "100 units; 7 breach the latency SLA; a Groth16 proof returns 0.07 MockUSDG to the client." },
  "B-anchored-dispute": { title: "Anchored mode with 20 on-chain acks and a dispute", description: "Each ack is a transaction hashed by the Stylus Poseidon program; 2 breaches; the proof is checked against the on-chain root." },
  "B-rollover": { title: "Rollover of 128 + 5 units on one deposit", description: "Epoch 0 fills (128 units), a cooperative rollover pays 2.56 MockUSDG, and epoch 1 serves 5 more units." },
  "B-cooperative": { title: "Cooperative close", description: "100 units and both parties sign the close. The breaches occur but are not penalised." },
  "A-complete": { title: "Binary escrow, complete", description: "Control. An ERC-8183-style evaluator releases everything to the provider." },
  "A-reject": { title: "Binary escrow, reject", description: "Control. The evaluator refunds everything to the client." },
  all: { title: "Run the four comparison rows", description: "Cooperative, dispute and both binary outcomes, back to back." },
};

/** Narrative step templates (API_CONTRACT §7.1, L1–L17). */
export const stepCopy = {
  legMeta: (client: string, addr: string) => `Leg for client ${client} (${addr})`,
  faucet: (n: string, client: string) => `Faucet minted ${n} ${TOKEN} to client ${client}`,
  offer402: (amt: string, channel: string) => `402 Payment Required: pay ${amt} ${TOKEN} to ${channel}, the predicted channel address (not yet deployed)`,
  providerOpens: "Provider opens the channel on the first ack (provider-side transaction)",
  servedCoSigned: (k: string, n: string) => `${k} of ${n} units served, each acked by a co-signed checkpoint (no transactions)`,
  servedOnChain: (k: string, n: string) => `${k} of ${n} units served, each acked on-chain`,
  finalAck: "Final ack delivered to the provider",
  disputeCoSigned: "Dispute opened: submit the highest co-signed checkpoint, then the penalty proof",
  disputeAnchored: "Dispute opened: start the close at the last on-chain ack, then the penalty proof",
  proof: (amt: string) => `Groth16 proof accepted: ${amt} ${TOKEN} back to the client`,
  provedIn: (seconds: string) => `proved in ${seconds} s`,
  windowLeft: (left: string) => `Challenge window: ${left} s left (anyone may answer with a higher checkpoint)`,
  fastForward: (s: string) => `Local chain: fast-forwarded ${s} s to the end of the challenge window`,
  watcherSettled: "Settled by the provider's watcher (settle is permissionless), so the client sent no transaction",
  watcherRaceLost: "The provider's watcher settled first, so the channel is already settled",
  epochServed: (k: string, max: string, e: string) => `${k} of ${max} units served in epoch ${e}`,
  epochFull: (e: string, max: string, amt: string, next: string) => `Epoch ${e} is full (${max} units). Rollover pays ${amt} ${TOKEN} and carries the rest into epoch ${next}.`,
  epochStarted: (e: string) => `Epoch ${e} started: sequence reset to 0, no new deposit`,
  servedAcrossEpochs: (k: string, n: string, m: string, e: string) => `${k} of ${n} units served (${m} in epoch ${e})`,
  gas: (g: string) => `${g} gas`,
};

/** Transaction labels (API_CONTRACT §7.2). Keys are the exact server labels. */
export const txCopy: Record<string, string> = {
  fund: "Fund the channel (MockUSDG transfer)",
  ack: "Ack the unit on-chain",
  submitCheckpoint: "Submit the highest co-signed checkpoint",
  startClose: "Start the close (anchored)",
  claimPenalty: "Claim the penalty with the Groth16 proof",
  settle: "Settle",
  closeCooperative: "Close cooperatively (both signatures)",
  rollover: "Roll over to the next epoch",
  openViaExit: "Open via the exit ticket",
  exitUnilateral: "Unilateral exit",
  approve: "Approve the escrow",
  "createJob (syarat di calldata)": "Create job (terms in plain calldata)",
  "submit (provider)": "Provider submits the work",
  "complete (evaluator = klien)": "Evaluator completes (evaluator = client)",
  "reject (evaluator = klien)": "Evaluator rejects (evaluator = client)",
};
export const escrowFundCopy = "Fund the escrow";

/** Result-row strings (API_CONTRACT §7.3). Keys are the exact server strings. */
export const rowCopy = {
  market: {
    "A: evaluator biner (complete)": "Market A: binary evaluator (complete)",
    "A: evaluator biner (reject)": "Market A: binary evaluator (reject)",
    "B: AegisClear kooperatif": "AegisClear: cooperative close",
    "B: AegisClear sengketa (bukti)": "AegisClear: dispute settled by proof",
    "B: AegisClear anchored (ack on-chain, sengketa)": "AegisClear anchored: on-chain acks, dispute",
    "B: AegisClear rollover (128 + 5 unit, 1 deposit)": "AegisClear rollover: 128 + 5 units, one deposit",
  } as Record<string, string>,
  decidedBy: {
    "alamat evaluator": "An evaluator address",
    "dua tanda tangan": "Two signatures",
    "bukti Groth16": "A Groth16 proof",
    "bukti Groth16 atas R on-chain": "A Groth16 proof over the on-chain R",
    "dua tanda tangan ×2 (rollover + close)": "Two signatures, twice (rollover and close)",
  } as Record<string, string>,
  visible: {
    "harga, ambang, penalti (string)": "Price, thresholds, penalty (plain text)",
    "T, R, jumlah": "T, R, amount",
    "T, R, jumlah, payToClient": "T, R, amount, payToClient",
    "hash daun, A per ack, payToClient": "Leaf hashes, A per ack, payToClient",
    "T, R, epoch, jumlah": "T, R, epoch, amount",
  } as Record<string, string>,
};

/** Global chrome (LAYOUT_SPEC navigation; README §7). */
export const shellCopy = {
  wordmark: "AegisClear",
  wordmarkSuffix: "console",
  nav: [
    { to: "/", label: "Desk" },
    { to: "/channels", label: "Channels" },
    { to: "/offer", label: "x402 offer" },
    { to: "/deployment", label: "Deployment" },
  ],
  menu: "Menu",
  liveRun: "Live run",
  testnetPlate: "Robinhood Chain testnet",
  localPlate: "Local chain",
  explorerDisabled: "explorer links disabled",
  fixtureBadge: "Fixture replay",
  fixtureDetail: "recorded data, no chain",
  fixtureSpeed: (speed: number) => `${speed}× speed`,
  theme: { system: "System theme", light: "Light theme", dark: "Dark theme" },
  themeSwitch: (current: string, next: string) => `${current}. Switch to ${next.toLowerCase()}`,
  skip: "Skip to content",
  footer: {
    testnet: "Robinhood Chain testnet",
    local: "Local private chain 31337",
    token: "MockUSDG (USDG-native design)",
    audit: "Self-audited, not independently audited",
    limits: "Known limits",
    source: "Source: github.com/mdlog/AegisClear",
  },
};

export const REPO_URL = "https://github.com/mdlog/AegisClear";
export const SERVE_TESTNET = "AEGIS_NETWORK=testnet pnpm --filter @aegisclear/web serve";
export const SERVE_LOCAL = "pnpm --filter @aegisclear/web serve";

/** Root states (LAYOUT_SPEC root-level states; README §7 baseline copy). */
export const serverDownCopy = {
  title: "Console server is not running",
  body: "Start it with one of these commands, then retry. The page you asked for opens as soon as the server answers.",
  testnet: "Robinhood Chain testnet (the demo)",
  local: "Local chain",
  retry: "Retry now",
  retrying: "Retrying",
  auto: (ago: string) => `Retrying automatically every 3 s. Last attempt ${ago}.`,
  noAnswer: "Nothing answered at /api/config.",
  answered: (status: number, code: string) => `/api/config answered ${status} (${code}).`,
};

export const rootErrorCopy = {
  title: "Something broke in the console UI",
  body: "This is a bug in the interface, not in the protocol. Reloading usually recovers; the chain and the server are unaffected.",
  reload: "Reload",
  details: "Error details",
  home: "Go to the Desk",
};

export const notFoundCopy = {
  title: "No page at this address",
  asked: "You asked for",
  suggestion: "Did you mean",
  links: "Pages in this console",
};

/** /deployment (LAYOUT_SPEC; PRODUCT_CONTEXT §5, §6). Static facts carry their source. */
export const deploymentCopy = {
  title: "Deployment",
  lede: "Where AegisClear runs and on what: the network, every contract, the parties, the measured facts and the known limits.",
  network: "Network",
  testnetName: "Robinhood Chain testnet",
  localName: "Local private chain 31337",
  chain: "Chain",
  rpc: "RPC URL",
  explorer: "Explorer",
  noExplorer: "No block explorer",
  deployBlock: "Deploy block",
  challengeWindow: "Challenge window",
  responseWindow: "Response window",
  deposit: "Market-B deposit",
  verified: "Deploy v2: 7/7 contracts verified on Blockscout",
  localNote: "Challenge windows are fast-forwarded on the local chain.",
  contracts: "Contracts",
  role: "Role",
  address: "Address",
  groups: { factories: "Channel factories", settlement: "Settlement", hashing: "Hashing", token: "Token", control: "Control", other: "Other" },
  parties: "Parties",
  provider: "Provider",
  client: (label: string) => `Client ${label}`,
  keys: "Keys are held by the console server. The browser holds none and never signs.",
  facts: "Measured facts",
  fact: "Fact",
  value: "Value",
  source: "Source",
  limits: "Known limits",
  sources: "Sources",
};

export const contractRoles: Record<string, (ctx: { challenge: number; network: string }) => { name: string; meaning: string; group: keyof typeof deploymentCopy.groups }> = {
  factory: ({ challenge }) => ({ name: "Channel factory (co-signed)", meaning: `Demo factory with a ${challenge} s challenge window`, group: "factories" }),
  factoryProd: () => ({ name: "Channel factory (co-signed, production)", meaning: "Production factory with a 6 h challenge window", group: "factories" }),
  factoryAnchored: () => ({ name: "Channel factory (anchored)", meaning: "Anchored mode: acks hashed by the Poseidon program", group: "factories" }),
  verifier: () => ({ name: "Groth16 verifier", meaning: "SLASettlementVerifier: checks the penalty proof inside claimPenalty", group: "settlement" }),
  router: () => ({ name: "Treasury router", meaning: "AegisTreasuryRouter: pays out to treasuries", group: "settlement" }),
  poseidon: ({ network }) => ({ name: "Poseidon hashing", meaning: network === "testnet" ? "The Stylus AegisPoseidon program" : "The Yul twin of the Stylus program (local chain)", group: "hashing" }),
  usdg: () => ({ name: "Token", meaning: "MockUSDG: a 6-decimal test stand-in; USDG-native design; mainnet 4663 is not deployed", group: "token" }),
  escrow: () => ({ name: "Binary escrow (control)", meaning: "SimpleJobEscrow: the Market A control", group: "control" }),
};

export const measuredFacts: { fact: string; value: string; source: string; deploymentSpecific?: boolean }[] = [
  { fact: "Groth16 verifier", value: "229,241 gas", source: "contracts/test/Verifier.t.sol" },
  { fact: "Circuit", value: "115,066 constraints; proving takes about 3.2 to 4.7 s", source: "docs/TOOLCHAIN.md, fixtures" },
  { fact: "Stylus", value: "Stylus is used only for anchored-mode Poseidon hashing: 1.75× cheaper than Yul, measured on-chain (insertPath 144,076 gas against 252,271; about 1.9× execution-only)", source: "docs/benchmarks/poseidon.md" },
  { fact: "Full-cycle gas, testnet", value: "Dispute 575,544; anchored 4,799,914; rollover 298,821; cooperative 182,452", source: "README, console run of 20 Sep 2026", deploymentSpecific: true },
  { fact: "Epoch", value: "128 units (MAX_SEQ)", source: "spec §6.6" },
];

export const knownLimits = [
  "The trusted setup has a single contributor, so a public ceremony is required before real funds. Loss is bounded on-chain by payToClient ≤ A.",
  "MockUSDG on testnet 46630; mainnet 4663 is not deployed yet.",
  "Self-audited only (Slither triage, 0 true High or Medium), not independently audited.",
  "The Mesh facilitator funding path is untested: the offer is x402-compatible, so facilitators need no change.",
  "The Stylus program needs a manual keepalive (365-day expiry). Funds stay recoverable through the pure-EVM close paths.",
];

/** Slot H3 (LAYOUT_SPEC honesty slots): closes every privacy surface. */
export const inferenceLine = "Terms and metrics stay private; amounts and timing are public. A ÷ seq reveals the average price and payToClient ÷ A the penalty share. AegisClear does not claim anonymity.";

export const sourceLinks = [
  { label: "Repository", href: REPO_URL },
  { label: "Proving key release v0.1.0-zkey", href: `${REPO_URL}/releases/tag/v0.1.0-zkey` },
  { label: "Stylus against Yul benchmarks", href: `${REPO_URL}/blob/main/docs/benchmarks/poseidon.md` },
  { label: "Slither self-audit", href: `${REPO_URL}/blob/main/docs/audit/slither-2026-09.md` },
];

/** /channels (LAYOUT_SPEC; README §6.6 table craft, §7 states). */
export const registryCopy = {
  title: "Channels",
  lede: "Every channel opened by this deployment's factories, newest first. Settled money lives in each channel's record, read from its Settled event.",
  count: (shown: number, total: number) => (shown === total ? `${total} channels` : `${shown} of ${total} channels`),
  scanned: (ago: string) => `Scanned ${ago}`,
  stale: (ago: string) => `The chain RPC didn't answer. Showing data from ${ago}; retrying.`,
  caption: "Channels on this deployment, newest first",
  filters: "Filter channels",
  state: "State",
  stateNames: { OPEN: "Open", CLOSING: "Closing", SETTLED: "Settled" } as Record<string, string>,
  mode: "Mode",
  modeNames: { "co-signed": "Co-signed", anchored: "Anchored" } as Record<string, string>,
  factory: "Factory",
  factoryNames: { factory: "Demo (co-signed)", factoryProd: "Production (co-signed)", factoryAnchored: "Anchored" } as Record<string, string>,
  client: "Client",
  clientNames: { A: "Client A", B: "Client B", other: "Other" } as Record<string, string>,
  any: "Any",
  session: "Created in this server session",
  clear: "Clear filters",
  columns: { channel: "Channel", client: "Client", mode: "Mode", state: "State", seq: "Seq", epoch: "Epoch", a: "A", budget: "Budget", proof: "Proof", opened: "Opened block" },
  ackedTotal: "Acked total (A), MockUSDG",
  budgetTitle: "Live token balance, MockUSDG",
  proofTitle: "Proven refund (payToClient), MockUSDG",
  splitLink: "Split in record",
  splitLabel: (addr: string) => `Split in the record for channel ${addr}`,
  channelLabel: (addr: string) => `Channel ${addr}`,
  runTag: "Run",
  thisRunTag: "This run",
  runTagLabel: (runId: string) => `Created by run ${runId} in this server session`,
  prodTag: "Production",
  prodTagTitle: "Production factory, 6 h challenge window",
  blocks: (label: string) => `Blocks new runs for client ${label}`,
  closingIn: (left: string) => `≈ ${left}`,
  none: "None",
  empty: "No channels yet",
  emptyBody: "Run a scenario to open the first one.",
  emptyAction: "Run a scenario",
  noMatch: "No channels match these filters",
  noMatchBody: (total: number) => `Clear the filters to see all ${total} channels.`,
  showAll: "Show all channels",
  loading: "Reading the channel registry",
  error: "The chain RPC didn't answer, so the registry could not be read. Retrying.",
  page: (n: number, of: number) => `Page ${n} of ${of}`,
  prev: "Previous page",
  next: "Next page",
  pages: "Registry pages",
};

/** /channels/:address (LAYOUT_SPEC; API_CONTRACT §4.1: money from Settled and RolledOver, never from A). */
export const recordCopy = {
  title: "Channel record",
  lede: "Everything the chain knows about one channel, read from its events, and what it does not know.",
  breadcrumb: "Breadcrumb",
  crumbChannels: "Channels",
  identity: "Identity",
  address: "Channel address",
  mode: "Mode",
  modeNames: { "co-signed": "Co-signed", anchored: "Anchored" } as Record<string, string>,
  factory: "Factory",
  factoryMeaning: {
    factory: (window: string) => `Demo factory with a ${window} challenge window`,
    factoryProd: (window: string) => `Production factory with a ${window} challenge window`,
    factoryAnchored: (stylus: boolean) => (stylus ? "Anchored factory: acks hashed by the Stylus Poseidon program" : "Anchored factory: acks hashed by the Poseidon program (Yul twin on the local chain)"),
  },
  epoch: "Epoch",
  stateLabel: "State",
  runLabel: "Run",
  client: "Client",
  clientLabel: (label: string) => `Client ${label}`,
  otherClient: "Not a demo client",
  createdByRun: (runId: string) => `Created by run ${runId} in this server session`,
  lifecycle: "Lifecycle",
  station: {
    Opened: "Opened by the provider",
    OpenedMeta: "factory.open",
    Acked: (n: number) => `${n} on-chain ack${n === 1 ? "" : "s"}`,
    AckedRange: (min: string, max: string) => (min === max ? `${min} gas` : `${min} to ${max} gas`),
    CheckpointSubmitted: "Highest co-signed checkpoint submitted",
    CloseStarted: "Close started over the on-chain state",
    windowStarted: "Challenge window started",
    PenaltyClaimed: "Penalty claimed with a Groth16 proof",
    penaltyMeta: (amt: string) => `${amt} back to the client`,
    RolledOver: (epoch: string) => `Rolled over to epoch ${epoch}`,
    rolledMeta: (paid: string, carried: string) => `${paid} to the provider, ${carried} carried`,
    Settled: "Settled",
    settledMeta: "Figures in the settlement below",
    open: "Open",
    openMeta: "Co-signed service leaves no on-chain trace until a checkpoint or close.",
    closing: (left: string) => `Challenge window ends in ${left}`,
    closingMeta: "Measured against this browser's clock; chain time can differ slightly.",
    deadlinePassed: "Deadline passed (chain time can differ slightly): settle() is now permissionless",
    showAcks: (n: number) => `Show all ${n} acks`,
    hideAcks: "Hide the acks",
  },
  block: (n: string) => `Block ${n}`,
  settlement: "Settlement",
  toProvider: "To the provider",
  toClient: "To the client",
  penalty: "Penalty",
  clientSplit: (refund: string, unused: string) => `${refund} proven refund and ${unused} unused deposit`,
  decidedProof: "Decided by a Groth16 proof",
  decidedProofAnchored: "Decided by a Groth16 proof over the on-chain R",
  decidedSignatures: "Decided by two signatures",
  proofTx: "The claimPenalty transaction",
  aZero: "A reads 0 on-chain for this channel; the split comes from the Settled event.",
  epochsCaption: "Settlement per epoch",
  epochCol: "Epoch",
  howCol: "How",
  providerCol: "To the provider",
  clientCol: "Carried or to the client",
  rollover: "Rollover",
  cooperativeClose: "Cooperative close",
  disputeClose: "Settled after a proof",
  settledClose: "Settled",
  carried: (amt: string) => `${amt} carried`,
  toClientAmt: (amt: string) => `${amt} to the client`,
  totals: (provider: string, client: string, deposit: string) => `Provider ${provider}, client ${client}, deposit ${deposit}`,
  totalRow: "Total",
  inEscrow: "In escrow",
  budget: "Live token balance",
  aSoFar: "A as last recorded on-chain",
  notSettled: "Not settled yet.",
  state: "On-chain state",
  kv: {
    seq: "Seq", epoch: "Epoch", a: "Acked total (A)", aNote: "As last recorded on-chain; settled channels can read 0.",
    budget: "Budget (live token balance)", t: "Terms commitment (T)", r: "Receipts root (R)", proof: "Proof",
    proofYes: (amt: string) => `Accepted: payToClient ${amt}`, proofNo: "None",
    windows: "Challenge and response windows", windowsValue: (challenge: string, response: string) => `${challenge} and ${response}`, payoutClient: "Client payout", payoutProvider: "Provider payout",
    samePayout: "Paid to the party itself", otherPayout: "Paid to a different address", router: "AegisTreasuryRouter",
    token: "Token", tokenMock: "MockUSDG", opened: "Opened", openedBlock: (b: string) => `block ${b}`, salt: "Salt",
  },
  events: "Event trail",
  eventCols: { n: "#", name: "Event", args: "Details", block: "Block", gas: "Gas", tx: "Transaction" },
  ackedGroup: (n: number) => `Acked, ${n} transactions`,
  argNone: "none",
  argDeadline: (utc: string) => `${utc} UTC (chain time)`,
  argProvider: "provider",
  argClient: (label: string) => `client ${label}`,
  anchoredNote: "Anchored mode puts each ack on-chain, so leaf hashes and the running total are public and the unit price can be inferred. Metrics and thresholds stay private.",
  yes: "yes",
  no: "no",
  privacy: "Privacy",
  factCol: "Fact",
  visibleCol: "Visible on-chain for this channel",
  privateCol: "Kept private",
  demoTerms: "demo session terms, known to both parties",
  privateOnly: "Private to the two parties; the console only knows the demo clients' terms.",
  anchoredCaveat: "anchored: leaf hashes and A per ack are visible on-chain (unit price implied); metrics and thresholds stay private.",
  leakFromRun: "Run the leak check from its run",
  leakNeedsRun: "A leak check needs the run that created this channel, and runs live only in this server session.",
  loading: "Reading the channel from the chain",
  invalid: "That is not an address",
  invalidBody: "A channel address is 0x followed by 40 hexadecimal characters.",
  unknown: "No channel at this address in this deployment's factories. Check the address or browse the registry.",
  contract: (role: string) => `This is the ${role} contract, not a channel.`,
  toDeployment: "See the deployment",
  toRegistry: "Browse the registry",
  notRecorded: "This channel is listed, but its detail was not recorded in the fixture set.",
  rpcDown: "The chain RPC didn't answer, so this channel could not be read. Retrying.",
  stale: (ago: string) => `The chain RPC didn't answer. Showing data from ${ago}; retrying.`,
};

/** /offer (LAYOUT_SPEC; API_CONTRACT §8; slot H5). */
export const offerCopy = {
  title: "x402 offer",
  lede: "The real 402 challenge a demo client receives, and why any x402 facilitator can settle into it unchanged.",
  clientLegend: "Client",
  client: (label: string) => `Client ${label}`,
  status: (code: number) => (code === 402 ? "402 Payment Required" : `HTTP ${code}`),
  session: "Current session offer.",
  sessionNote: "After a run finishes this endpoint keeps returning that session's offer, whose payTo may already be SETTLED, until the next run resets it.",
  facilitator: "What any x402 facilitator sees",
  aegis: "What only the AegisClear client reads",
  aegisKey: "extra.aegis",
  x402Version: "The x402 protocol version.",
  scheme: "Pay the exact amount to payTo. Nothing new for the facilitator.",
  network: (name: string) => name,
  networkNames: { 46630: "Robinhood Chain testnet", 31337: "Local private chain" } as Record<number, string>,
  asset: (named: boolean) => (named ? "MockUSDG, the token of this deployment" : "A token that is not this deployment's MockUSDG"),
  payTo: "Predicted CREATE2 channel address. No contract exists here until the provider opens it, and it can only ever become a channel with exactly these signed terms.",
  notYet: "Not yet a channel: nothing is deployed at this address.",
  already: (state: string) => `Already a channel (${state}). This offer belongs to the previous session; the next run issues a new one.`,
  openChannel: "Open channel",
  deposit: (amt: string) => `${amt} deposit`,
  windows: (challenge: string, response: string) => `${challenge} and ${response}`,
  config: "The channel config the provider signed: client, provider, token, terms commitment T, windows, payouts and salt.",
  sigProvider: "The provider's EIP-712 signature over this config.",
  terms: "Sent to the client only: private from the chain, not from the counterparty.",
  termsValues: (price: string, latency: string, quality: string, penalty: string, cap: string) =>
    `Unit price ${price}, latency ≤ ${latency} ms, quality ≥ ${quality}, penalty ${penalty} of the unit price per breaching unit, cap ${cap} of A.`,
  nonce: "Session nonce (part of the terms, hidden inside T).",
  unitQty: "Units per request.",
  exitSig: "A pre-signed seq-0 exit ticket: the client can always leave.",
  anchored: (on: boolean) => (on ? "Anchored mode: every ack is an on-chain transaction." : "Co-signed mode: acks are off-chain signatures."),
  caveat: "x402-compatible offer: facilitators need no change (untested with Mesh).",
  raw: "Raw 402 response",
  copyJson: "the raw 402 JSON",
  unexpected: "Unexpected offer shape, showing the raw response.",
  loading: "Asking the provider for a fresh offer",
  invalidClient: "Client must be A or B",
  failed: "The console server could not produce an offer. Retrying.",
};

/** Scenario buttons say exactly what happens (README §7). */
export const runLabel: Record<ScenarioId, string> = {
  "B-dispute": "Run dispute",
  "B-anchored-dispute": "Run anchored dispute",
  "B-rollover": "Run rollover",
  "B-cooperative": "Run cooperative close",
  "A-complete": "Run binary complete",
  "A-reject": "Run binary reject",
  all: "Run all four",
};

/** Start errors (README §7 baseline copy, API_CONTRACT §9). */
export const startErrorCopy = {
  busy: "Another run is in progress.",
  busyBody: "One scenario runs at a time.",
  openRunning: "Open the running scenario",
  openChannel: (label: string, short: string) => `Client ${label} still has an open channel (${short}).`,
  openChannelBody: "It must settle before this client can start a new run. On testnet an OPEN, unfunded channel can remain after a failed run.",
  openChannelLink: "Open channel",
  preflight: "The scenario could not start.",
  preflightBody: "The server reported:",
  unreachable: "The console server did not answer. Check that it is running, then try again.",
  other: (code: string) => `The server refused the run (${code}).`,
};

/** / Desk (LAYOUT_SPEC; PRODUCT_CONTEXT §1, §6). */
export const deskCopy = {
  problem: "Agents on Robinhood Chain already pay each other in USDG over x402 exact: pay first, receive later, no recourse.",
  answer: "AegisClear puts an escrow at the x402 payTo address and settles SLA disputes with a Groth16 proof, not a judge.",
  evidence: "MeshGateway today",
  evidenceFigures: [
    { value: "1,030", label: "storefronts" },
    { value: "15,718", label: "on-chain settlements" },
    { value: "512.48 USDG", label: "lifetime volume" },
    { value: "0.033 USDG", label: "average payment" },
  ],
  evidenceSource: "Source: spec §2.3, read 19 Sep 2026.",
  railsTitle: "Three rails",
  railsCaption: "Same job on three rails: 100 requests at 0.02 USDG, 7 breach the 800 ms latency SLA",
  railCols: { rail: "Rail", back: "What the client gets back", decides: "Who decides", sees: "What the public chain sees" },
  rails: {
    x402: { name: "x402 exact (today)", back: "Nothing: 2.00 is gone", decides: "Nobody", sees: "Every transfer" },
    binary: { name: "ERC-8183-style binary escrow", back: "0 or 2.00", decides: "A trusted evaluator", sees: "The terms and the reason, in plain text" },
    aegis: { name: "AegisClear", back: (client: string, provider: string) => `${client} back, ${provider} to the provider`, decides: "A Groth16 proof", sees: "Two commitments and the final split" },
  },
  worked: "Worked example (spec §6.5)",
  prove: "Prove it live",
  seenLive: (runId: string) => `Seen live in run ${runId}`,
  provedIn: (s: string) => `Proved in ${s} s.`,
  onChain: (n: number, network: string) => `${n} channels on ${network}:`,
  onChainState: (n: number, state: string) => `${n} ${state}`,
  scanned: (ago: string) => `Scanned ${ago}.`,
  stateWords: { SETTLED: "settled", OPEN: "open", CLOSING: "closing" } as Record<string, string>,
  networkName: (network: string) => (network === "local" ? "the local chain" : "Robinhood Chain testnet"),
  liveTitle: "Live run",
  latestTitle: "Latest run",
  latestError: (title: string) => `Stopped with an error: ${title}`,
  openRun: "Open run",
  launcher: "Run a scenario",
  launcherLede: "Each run drives the two demo clients with keys held by the console server.",
  oneAtATime: "One run at a time, server-wide.",
  openLive: "Open the live run",
  groups: { aegisclear: "AegisClear", control: "Binary escrow (control)", both: "Full comparison" },
  client: (c: string) => (c === "A and B" ? "Clients A and B" : `Client ${c}`),
  expected: "Expected split",
  expectedValue: (v: string) => (v === "4 rows" ? "4 result rows" : `${v} (client / provider)`),
  duration: "Takes",
  durationFeatured: (d: string, challenge: number, testnet: boolean) => (testnet ? `${d} on testnet, including the ${challenge} s challenge window` : `${d} on the local chain`),
  mode: "Mode",
  modeNames: { "co-signed": "Co-signed", anchored: "Anchored", escrow: "Binary escrow", mixed: "Co-signed and binary escrow" } as Record<string, string>,
  starting: "Starting",
  sessionRuns: "Session runs",
  sessionCaption: "Kept in server memory only: cleared on every restart (max 50).",
  sessionCols: { scenario: "Scenario", client: "Client", status: "Status", started: "Started", duration: "Duration", result: "Result", channels: "Channels" },
  noRuns: "No runs in this server session yet.",
  loadingRuns: "Reading the session runs",
  fourRows: "4 rows",
};

/** /runs/:runId, the clearing tape (LAYOUT_SPEC; API_CONTRACT §5; DESIGN_BRIEF §5 slip). */
export const runCopy = {
  crumbDesk: "Desk",
  crumb: (id: string) => `Run ${id}`,
  client: (c: string) => (c === "A and B" ? "Clients A and B" : `Client ${c}`),
  runId: "Run id",
  elapsed: "Elapsed",
  duration: "Duration",
  reconnecting: "Reconnecting: the run stream dropped, so the console polls the server every 2 s. The tape keeps what it has.",
  starting: "Starting: waiting for the first step.",
  nextAction: "Next action",
  nextActionLive: "One run at a time, server-wide.",
  clientLabel: "Client",
  statusLabel: "Status",
  runAnother: "Run another scenario",
  openRecord: (short: string) => `Open channel record ${short}`,
  copyRecovery: "Copy recovery link",
  recoveryCopied: "Recovery link copied",
  rail: "Lifecycle",
  station: {
    fund: "Fund", open: "Open", serve: "Serve", serve0: "Serve epoch 0", rollover: "Rollover", serve1: "Serve epoch 1",
    resolve: "Resolve", settle: "Settle", close: "Cooperative close", approve: "Approve", createJob: "Create job",
    fundEscrow: "Fund escrow", submit: "Provider submits", evaluateComplete: "Evaluator completes", evaluateReject: "Evaluator rejects", other: "Other",
  },
  stationState: { pending: "pending", current: "in progress", done: "done", stopped: "stopped here" },
  tx: (n: number) => `${n} tx`,
  units: (n: number, tx: number) => `${n} units, ${tx} tx`,
  providerTx: "provider tx",
  legOf: (n: number, of: number) => `Leg ${n} of ${of}`,
  acts: { fund: "Fund", service: "Serve", resolution: "Resolve", close: "Close", escrow: "Binary escrow (control)", other: "Other steps" },
  showAct: "Show the steps",
  hideAct: "Hide the steps",
  gridTitle: "Private receipts, co-signed off-chain",
  gridLabel: (filled: number, slots: number, breaches: number) => `Receipt grid: ${filled} of ${slots} slots filled, ${breaches} breaching units marked`,
  serviceTx: "On-chain transactions during service",
  breachDispute: "Breaching units are the parties' private knowledge and the proof's input.",
  breachClosed: "Breached, not disputed: the client signed the close.",
  unitsServed: (k: number, n: number) => `${k} of ${n} units served`,
  ackTitle: "Acks on-chain, one transaction each",
  ackSlot: (seq: number) => `Ack ${seq}`,
  stylus: "Stylus is used only for anchored-mode Poseidon hashing: 1.75× cheaper than Yul, measured on-chain.",
  epochTitle: (e: number, k: number, max: number) => `Epoch ${e}: ${k} of ${max} units`,
  closeSigned: "Both parties signed the close: settled at once, no challenge window.",
  calldataFlag: "The leak being contrasted: the terms travel in plain calldata.",
  resolution: "Resolution",
  r: {
    opened: "Dispute opened",
    openedCoSigned: "Submit the highest co-signed checkpoint, then the penalty proof.",
    openedAnchored: "Start the close at the last on-chain ack, then the penalty proof.",
    state: "State submitted on-chain",
    stateMeta: "Starts the challenge window.",
    proof: "Groth16 proof",
    proofStatement: (amt: string) => `Under the committed terms T and the co-signed receipts R, the lawful refund is ${amt} MockUSDG.`,
    proofVerified: "Verified on-chain inside claimPenalty (verifier 229,241 gas).",
    claim: "Penalty claimed",
    window: "Challenge window",
    settled: "Settled",
    pending: "Submitting the state, generating the Groth16 proof (typically 3 to 5 s) and claiming the penalty.",
    pendingSince: (s: string) => `${s} since the dispute opened`,
    waiting: "Waiting",
    left: (s: number) => `${s} s left`,
    deadlinePassed: "Deadline passed: settle() is now permissionless. Waiting for the settle transaction.",
    facts: [
      "Anyone may answer with a higher co-signed checkpoint during the window. It replaces this state and cancels the pending proof.",
      "After the deadline, settle() is permissionless: the provider's watcher, or anyone, can call it.",
    ],
    factWindow: (demo: number) => `This demo factory enforces a ${demo} s window; the production factory uses 6 h.`,
    summary: "Resolved by proof",
    summaryRefund: (amt: string) => `${amt} MockUSDG back to the client`,
    summaryProof: (s: string) => `1 proof, ${s} s`,
    summaryWindow: (s: number) => `${s} s window`,
  },
  context: {
    offerTitle: "The offer being funded",
    payTo: "payTo: the predicted channel address, not deployed until the provider's first ack.",
    deposit: "Deposit",
    offerLink: "Read the whole offer",
    seenTitle: "What the chain has seen so far",
    clientTx: "Client transactions",
    providerOpen: "The provider's open (visible as Opened in the channel record)",
    served: "Units served",
    chainTitle: "Chain sees now",
    reading: "Reading the chain…",
    deadline: "Deadline",
    polled: "Read from the channel every 5 s until it settles.",
    state: "State",
    settled: "Settled",
  },
  log: (n: number) => `All ${n} steps (server log)`,
  logCols: { t: "Elapsed", phase: "Phase", step: "Step", tx: "Transaction", gas: "Gas" },
  verdict: "Verdict",
  slip: {
    stub: "Held by provider and client",
    chain: "Visible on Robinhood Chain",
    chainLocal: "Visible on the local chain",
    client: "Client",
    provider: "Provider",
    acked: (a: string) => `A = ${a} MockUSDG`,
    barLabel: (a: string, p: string, c: string) => `A = ${a} MockUSDG: ${p} to the provider, ${c} to the client`,
    unspent: (amt: string) => `Unspent deposit ${amt} MockUSDG returned to the client`,
    deposit: (d: string, p: string, c: string, refund: string, unused: string) => `Deposit ${d} = ${p} to the provider + ${c} to the client (${refund} proven refund + ${unused} unused)`,
    depositSigned: (d: string, p: string, c: string) => `Deposit ${d} = ${p} to the provider + ${c} to the client`,
    binary: "Binary escrow (control): the only two possible outcomes",
    complete: "Complete: 0 / 2.00",
    reject: "Reject: 2.00 / 0",
    seenLive: "Seen live",
    runControl: "Run the control",
    decidedBy: "Decided by",
    proving: "Proving",
    gas: "Full-cycle gas",
    why: "Why",
    whyLine: (n: number, pct: string, price: string, refund: string, cap: string, capAmt: string, binding: boolean) =>
      `${n} breaching units × ${pct} of ${price} = ${refund}; cap ${cap} of A = ${capAmt}, ${binding ? "binding" : "not binding"}.`,
    whyCaption: "Computed privately inside the circuit; the chain only verified the proof.",
    notDisputed: "Not disputed: the client signed the close, so the breaches were not penalised.",
    nonce: "The session nonce never leaves the server.",
    anchoredPrice: "Implied on-chain by A per ack; excluded from the scan.",
    hiddenT: "Hidden inside the terms commitment T",
    hiddenR: "Hidden inside the receipts root R",
    sealCaption: "Drawn from the public hash. The same hash always draws the same seal; it cannot be read back into the terms.",
    notFound: (n: number) => `Not found in ${n} transactions`,
    factCol: "Fact",
    mirrorLabel: "Private terms against what Robinhood Chain shows",
  },
  leak: {
    idle: "Scan every transaction of this channel for these private values.",
    action: "Check for leaks",
    pending: "Scanning calldata and logs of every transaction of this channel…",
    leaks: "Leaks",
    ambiguous: "Ambiguous",
    scanned: "Transactions scanned",
    none: "Price, thresholds, penalty, cap, nonce and metrics appear nowhere on-chain.",
    anchored: "Unit price is not in the scanned set for anchored channels: A per ack already implies it.",
    txs: "Scanned transactions",
    found: "Found on-chain",
    failed: "Could not read the chain.",
    retry: "Retry the leak check",
    announce: (leaks: number, n: number) => `Leak check: ${leaks} leaks in ${n} transactions`,
  },
  calldata: {
    title: "Market A put the terms in plain calldata",
    body: "The binary escrow writes the job's terms into its createJob transaction, readable by anyone on the explorer:",
    quote: "100 units @ 0.02 USDG; maxLatency 800ms; minQuality 90; penalty 50%; cap 30%",
    caption: "As sent by the control scenario.",
    tx: "The createJob transaction",
    compare: "Compare with AegisClear: run the dispute",
  },
  results: "Result",
  resultCols: { market: "Market", split: "Client / Provider (MockUSDG)", decided: "Decided by", visible: "Readable on the explorer", gas: "Full-cycle gas", proving: "Proving", txs: "Transactions" },
  resultGroups: { control: "Binary escrow (control)", aegis: "AegisClear" },
  verdictRow: "Verdict row",
  na: "n/a",
  evidence: "Evidence tape",
  tabs: "Channels of this run",
  tab: (title: string) => title,
  announceDone: (client: string, provider: string) => `Run finished: ${client} back to the client, ${provider} to the provider`,
  announceProof: "Proof verified on chain",
  announceSettled: "Settled",
  announceError: "The run stopped with an error",
  errorTitle: "The run stopped with an error",
  errorDetails: "Server message",
  errorChannel: "This client may still hold an OPEN channel; new runs for this client are refused until it settles.",
  goneTitle: "This run is no longer in the console's memory",
  goneBody: "The server restarted, or the run is older than the last 50.",
  goneChannel: "Its channel is on-chain and permanent: the split and the proof survive there. The leak check does not, because it needs the run.",
  goneChannelLink: "Open the channel's settlement",
  invalidTitle: "That is not a run id",
  invalidBody: "A run id looks like mudg1f4b-60a0fd.",
  startNew: "Start a new run",
  browse: "Browse channels",
  unreachable: "The console server did not answer, so the run could not be read.",
};

/** The shortcut list (LAYOUT_SPEC "Keyboard"; README §1.1 C8). Every key has a visible equivalent on the page. */
export const shortcutsCopy = {
  button: "Shortcuts",
  title: "Keyboard shortcuts",
  keys: [
    { key: "n", action: "Go to the Desk and focus the featured Run.", scope: "Same as the Run buttons on the Desk." },
    { key: "r", action: "Open the live run, else the latest run.", scope: "Same as the live-run chip and the latest-run card." },
    { key: "l", action: "Run the leak check.", scope: "On a finished run with a channel; same as Check for leaks." },
    { key: "?", action: "Show this list.", scope: "Same as the Shortcuts button." },
    { key: "Esc", action: "Close the open menu or this list.", scope: "" },
  ],
  toggle: "Single-key shortcuts",
  toggleHelp: "Turn them off if they clash with a screen reader or speech input. Every action stays one click away on the page.",
  close: "Close",
  noRun: "No run yet",
};

/** Browser tab titles (WCAG 2.4.2): the page, then the console. */
export const pageTitle = (page: string) => `${page} – AegisClear console`;
export const titles = {
  desk: "Desk",
  channels: "Channels",
  channel: (short: string) => `Channel ${short}`,
  run: (title: string, id: string) => `${title}, run ${id}`,
  offer: "x402 offer",
  deployment: "Deployment",
  notFound: "No page at this address",
  serverDown: "Console server is not running",
};

export const followCopy = {
  jump: "Jump to live",
};
